Feature/cv2 2734 alerts with buttons
meedan/check-web pull request #1358
Opened 2023-03-06 19:05 UTC by danielevalverde

## Description

Refactoring to use only one Alert component instead of SucessAlert and WarningAlert components and pass the type of alert to Alert component as prop.
add small button and dismiss props to Alert
and fix tests

Reference: CV2-2734

## Type of change

- [ ] Performance improvement and/or refactoring (non-breaking change that keeps existing functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Automated test (add or update automated tests)

## Checklist

- [X] I have performed a self-review of my own code
- [ ] I have commented my code in hard-to-understand areas, if any
- [ ] I have made needed changes to the README
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] If I implemented any new components, they are self-contained, their `propTypes` are declared and they use React Hooks and, if data-fetching is required, they use Relay Modern with fragment containers
- [ ] I have removed the /* eslint-disable @calm/react-intl/missing-attribute */ from any files I've worked on and added a `description` prop to all `<FormattedMessage />` components that were missing it.
- [ ] To the best of my knowledge, any new styles are applied according to the design system
- [ ] If I added a new external dependency, I included a rationale for doing so and an estimate of the change in bundle size (e.g., checked in https://bundlephobia.com/)

2023-03-06 19:21 UTC, danielevalverde commented on src/app/components/cds/alerts-and-prompts/Alert.js
> +/* eslint-disable-line no-unused-vars */
Thanks for catching :) 
deleted :pray:

2023-03-06 20:01 UTC, brianfleming commented
@danielevalverde thanks! any tips or suggestions on how to review the output of this component visually? so i can see all the variations, etc?

2023-03-06 20:27 UTC, danielevalverde commented
> @brianfleming 

I think the easiest way is  change the type of alert here: 
by "warning" , "info", "error"
https://github.com/meedan/check-web/blob/feature/CV2-2734-alerts-with-buttons/src/app/components/team/SmoochBot/SmoochBotNewsletterEditor.js#L226

you can also pass the booelan props "dismiss" and the content of small button as the  "button" prop. 
and go to the "settings/tipline" page on the "Newsletter" tab where you will be able to see the Alert 

Happy to make a call and share my screen :)

2023-03-07 15:17 UTC, brianfleming requested changes
@danielevalverde nice progress! I have a couple nits and one suggestion.

- [ ] The drop shadow is missing when the bool is provided. It should include `box-shadow: 0 4px 16px rgba(0, 0, 0, 0.1);`
- [ ] It looks like the title is getting conflicting font sizes, should be `subtitle2` but it looks like its being overwritten by multiple type sizes being applied
- [ ] The color of the X dismiss should follow the theme of the alert, so either `validationSecondary`, `errorSecondary`, `alertSecondary`, or `brandSecondary`
- [ ] Can you change the warning icon to be the `report_problem` icon from mat icons? its a triangle instead of cirlce
- [ ] another nit about the icons ^, they should be the same color as the title element
- [ ] when there is a button present, the bottom padding on the alert is too large. This is because the button has a bottom margin, making the space larger. I suggest removing the bottom margin so the padding around the content is consistent:
<img width="218" alt="Screenshot 2023-03-07 at 9 57 12 AM" src="https://user-images.githubusercontent.com/418001/223459830-8f3d1e6a-59ae-491a-b8bd-7c7d1d056dac.png">

- [ ] to go along with that previous comment ^, the gap between the button and the content is a bit tight. I think its `8px` now, could you up it to `12px`?
- [ ] could you move the X button a bit so it lines up with the content and other icon, vertically? see the red line below:
<img width="820" alt="Screenshot 2023-03-07 at 9 59 37 AM" src="https://user-images.githubusercontent.com/418001/223460266-9edc0a02-5078-45ba-828b-9b3821fff092.png">

- [ ] there should be a "gutter" for the content on the right so, when it wraps it doesnt flow in to the X dismiss button. If you look at this mock up, the designs on the left versus what is in this branch on the right, you will see how the content runs into the X and below it.
<img width="541" alt="Screenshot 2023-03-07 at 10 11 40 AM" src="https://user-images.githubusercontent.com/418001/223463922-4de332a5-e0e0-43e9-96e0-dac6a2b5ad86.png">

### Suggestion:
- thanks for the tip on testing this. Another way to test the "toast" version would be to replace this component with your new one, since we would like to use your new component in this location as well:
<img width="398" alt="Screenshot 2023-03-07 at 9 54 21 AM" src="https://user-images.githubusercontent.com/418001/223462774-b130e41f-b02f-4103-88f7-771e604561fd.png">

Thanks! let me know if you would like to discuss or if I can provide any additional details on these changes.

2023-03-09 15:15 UTC, amoedoamorim commented
> ### Suggestion:
> * thanks for the tip on testing this. Another way to test the "toast" version would be to replace this component with your new one, since we would like to use your new component in this location as well:
> 
> <img alt="Screenshot 2023-03-07 at 9 54 21 AM" width="398" src="https://user-images.githubusercontent.com/418001/223462774-b130e41f-b02f-4103-88f7-771e604561fd.png">

@brianfleming Let's leave this change for a new ticket and assess feasibility first as it may not be a trivial change.

2023-03-09 17:04 UTC, danielevalverde commented
@brianfleming Thank you for the detailed review :pray: 

I fixed the items you listed, but please let me know if it is still missing something. 

Also: please noticed i change some prop names:
button -> buttonLabel
It is no longer necessary to pass  "dismiss" prop, it is just necessary to pass the "onClose" function, like we have here: 
https://github.com/meedan/check-web/blob/feature/CV2-2734-alerts-with-buttons/src/app/components/team/SmoochBot/SmoochBotNewsletterEditor.js#L227

2023-03-09 17:42 UTC, dariusk commented
This looks great overall! I have one piece of feedback to make the code a little easier to read. The `Alert` component accepts a `type` prop, which references an `alertTypes` object that has all the different variables for styles for each alert in it. This is good, but then you call `alertTypes[type].icon`, `alertTypes[type].primaryColor`, etc.

Near the top of the main `Alert` function, right after you call `useStyles`, you could do something like this:

`const {icon, primaryColor, secondaryColor, borderInfo} = alertTypes[type];`

This uses a [destructuring assignment](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment#description) in case you aren't familiar with that JS concept. Basically it lets you pull out the named properties of an object (in this case one of the sub-objects of `alertTypes`) into variables of the same name as each property. So now we have `borderInfo`, `primaryColor`, etc, set to variables on the main scope of `Alert`.

Then in the code you could just refer to variables themselves without `alertTypes[type]`, so for example lines 93-100 could look like

```jsx
  return (
    <Box
      className={[classes.box, 'alert'].join(' ')}
      style={{
        background: primaryColor,
        border: hasBorder ? borderInfo : null,
        boxShadow: hasBorder ? '0 4px 16px rgba(0, 0, 0, 0.1)' : null,
      }}
```

...notice how there is just `primaryColor` and `borderInfo` here instead of needing to address the `alertTypes`.

So you could just delete all occurrences of `alertTypes[type]` for clearer code.

2023-03-09 17:44 UTC, dariusk requested changes
(See above comment on destructuring for the "official" review)

2023-03-09 19:12 UTC, danielevalverde commented
> (See above comment on destructuring for the "official" review)

@dariusk, Thank yoou :heart: 
Applied your review :pray:

2023-03-09 19:15 UTC, merged

2023-03-09 19:34 UTC, brianfleming commented
Everything I mentioned looks like it was taken care of @danielevalverde thanks. I didn't get a chance to add another review before this was merged (did you mean to merge without approvals?), anyway, I would have added:

- the dismiss X should have a tooltip so the user knows what will happen if its clicked

2023-03-09 19:39 UTC, danielevalverde commented
I merged the progress, but i can keep work on it, Brian :) 
Will add the Tooltip. Thanks :pray: