Super user screens (now with a fix)
meedan/check-web pull request #1527
Opened 2023-07-19 18:00 UTC by dariusk

New PR for the fix to the errors on live. The problem was our `helpers.js` function `getSuperAdminMask()`.

This is a tricky one -- `localStorage` only stores strings, and casts `true` to `'true'` and `false` to `'false'`. So you might think that checking `superAdminMaskSession !== 'false'` would tell you if it was true, but in fact you need `superAdminMaskSession === 'true'` -- this is because in the case where `superAdminMaskSession` is not set at all, you get `null`. 

So regular users who had never touched `superAdminMaskSession` in their local storage would get `null`, which does not equal `'false'`, so the code thought the screen should show because `'false' !== null`. This is why regular users were seeing the super admin screen on content (but not the super admin controls at the bottom!)

2023-07-24 16:52 UTC, amoedoamorim requested changes
Great catch @dariusk ! It looks like this bug was introduced by the addressing of my review of the original PR ! :facepalm:  Please just fix this minor casing issue.

2023-07-25 17:48 UTC, melsawy commented on src/app/helpers.js
> +  return superAdminMaskSession === 'true';
no I should keep !== 'false' but handle a case for non super admin users

2023-07-25 17:49 UTC, melsawy commented on src/app/components/media/SuperAdminControls.js
> +  const maskSession = superAdminMaskSession !== 'false';
I kept it and handle a non super admin users https://github.com/meedan/check-web/pull/1527/commits/03eed84f7fe4a4eea49555974af29a46302dec65

2023-07-25 18:01 UTC, dariusk commented on src/app/helpers.js
> +  return superAdminMaskSession === 'true';
@amoedoamorim This does work given the commit that @melsawy linked. The bug had to do with the initial state of `localStorage` for non-superadmins, but Sawy's code skips `localStorage` entirely and assumes `false` if you're not a superadmin. I tested locally in a clean browser with a non-superadmin user and it does seem to work as designed.

2023-07-25 18:02 UTC, dariusk commented on src/app/components/media/SuperAdminControls.js
> +  const maskSession = superAdminMaskSession !== 'false';
Tested locally and it works well given the routing around `localStorage` for non-superadmins.

2023-07-25 18:03 UTC, dariusk commented
@amoedoamorim I can't approve my own PR but let me know if my explanation didn't make sense!

2023-07-25 19:13 UTC, amoedoamorim approved these changes

2023-07-25 19:20 UTC, merged