Feature/3367 replace legacy tags
meedan/check-web pull request #1615
Opened 2023-09-11 21:34 UTC by amoedoamorim

## Description

Refactoring MediaTags with Relay Modern and making use of TagList cds component.

Changelist:
- Added onClick prop to Chip to allow click to search by tag
- Removed older MediaTags_projecMedia fragment references
- Refactored MediaTags with Relay Modern QueryRenderer and mutations
- Deprecated TagMenu component
- Deprecated relay classic tag mutations

References: CV2-3367

## Type of change

- [x] Performance improvement and/or refactoring (non-breaking change that keeps existing functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Automated test (add or update automated tests)

## How has this been tested?

Tested manually that adding and removing tags to an item works as expected.
Also clicking a tag to search by that tag also still works.

## Things to pay attention to during code review

- Are fragments in tags still relevant? Fragments were related to video tags, which it was used to tag segments of a video.

## Checklist

- [x] I have performed a self-review of my own code
- [x] I've made sure my branch is runnable and given good testing steps in the PR description
- [ ] I have commented my code in hard-to-understand areas, if any
- [ ] I have made needed changes to the README
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] If I implemented any new components, they are self-contained, their `propTypes` are declared and they use React Hooks and, if data-fetching is required, they use Relay Modern with fragment containers
- [x] I have removed the /* eslint-disable @calm/react-intl/missing-attribute */ from any files I've worked on and added a `description` prop to all `<FormattedMessage />` components that were missing it.
- [ ] To the best of my knowledge, any new styles are applied according to the design system
- [ ] If I added a new external dependency, I included a rationale for doing so and an estimate of the change in bundle size (e.g., checked in https://bundlephobia.com/)

2023-09-11 22:07 UTC, amoedoamorim commented
Pending fixing unit tests

2023-09-11 22:13 UTC, caiosba commented
Answering questions in the PR: We don't need fragments anymore, it was only used by the video player.

2023-09-11 22:17 UTC, caiosba commented on src/app/components/media/MediaTags.js
> +    console.log('failed to create or delete tags'); // eslint-disable-line
Can we replace this by the regular flash component?

2023-09-11 22:17 UTC, caiosba commented on src/app/components/media/MediaTags.js
> +  // const options = projectMedia.team.tag_texts.edges.map(tt => ({ label: tt.node.text, value: tt.node.text }));
Do we need to keep these comments?

2023-09-11 22:17 UTC, caiosba commented on src/app/components/media/MediaTags.js
> +            #  }
Do we need to keep these comments?

2023-09-12 17:49 UTC, caiosba requested changes
I left a few comments.

2023-09-13 00:05 UTC, amoedoamorim commented
@caiosba Ready for review

2023-09-13 00:13 UTC, caiosba approved these changes
Thanks for addressing the review comments!

2023-09-13 01:25 UTC, merged