Fix/cv2-3693: cannot restore or mark as not spam within items
meedan/check-web pull request #1630
Opened 2023-09-19 15:48 UTC by danielevalverde

## Description

Re-adding: restore from trash/mark as not spam" button on item page and removing deprecated code related to "confirm" items

Reference: CV2-3693

## Type of change

- [ ] Performance improvement and/or refactoring (non-breaking change that keeps existing functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Security mitigation or enhancement
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Automated test (add or update automated tests)

## How has this been tested?

- Send an item to the trash
- Go to the item page
Check that the button to "Restore From Trash" is displayed 
- click on the button
Check that the item is restored 

- Mark an item as Spam
- Go to the item page
Check that the button to "Mark as Not Spam" is displayed 
- click on the button
Check that the item is restored 

## Checklist

- [X] I have performed a self-review of my own code
- [ ] I've made sure my branch is runnable and given good testing steps in the PR description
- [ ] I considered secure coding practices when writing this code. Any security concerns are noted above.
- [ ] I have commented my code in hard-to-understand areas, if any
- [ ] I have made needed changes to the README
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] If I implemented any new components, they are self-contained, their `propTypes` are declared and they use React Hooks and, if data-fetching is required, they use Relay Modern with fragment containers
- [ ] I have removed the /* eslint-disable @calm/react-intl/missing-attribute */ from any files I've worked on and added a `description` prop to all `<FormattedMessage />` components that were missing it.
- [ ] To the best of my knowledge, any new styles are applied according to the design system
- [ ] If I added a new external dependency, I included a rationale for doing so and an estimate of the change in bundle size (e.g., checked in https://bundlephobia.com/)

2023-09-19 17:55 UTC, amoedoamorim requested changes
Looks great, Dani!! Please address these two comments for a :100:

2023-09-19 17:55 UTC, amoedoamorim commented on src/app/components/media/RestoreProjectMedia.js
> +      // FIXME: Add onFailure handler
Please add an onFailure handler

2023-09-19 17:55 UTC, amoedoamorim commented on src/app/components/media/RestoreProjectMedia.js
> +/* eslint-disable relay/unused-fields */
Please remove this directive and weed out unused query fields

2023-09-19 17:55 UTC, brianfleming reviewed
@danielevalverde not sure if I am missing a detail, but I noticed there is a type of item that I can send to spam, but not restore on the item page:

### In Spam
<img width="365" alt="Screenshot 2023-09-19 at 1 53 53 PM" src="https://github.com/meedan/check-web/assets/418001/3458fdfc-5e85-441b-962a-27e23d18f2c7">

### Item page, no restore button:
<img width="1663" alt="Screenshot 2023-09-19 at 1 53 59 PM" src="https://github.com/meedan/check-web/assets/418001/5edf2547-56f8-4a0f-9f4d-fcea84be5ac0">

Is there a reason that I am overlooking?

2023-09-19 17:58 UTC, brianfleming commented
@danielevalverde Same comment for the trash, same item when moved to the trash cannot be restored from the item page

2023-09-19 18:18 UTC, brianfleming requested changes

2023-09-19 18:18 UTC, brianfleming commented on src/app/components/media/RestoreProjectMedia.js
> +import Button from '@material-ui/core/Button';
Could you update this to the cds ButtonMain component please

2023-09-19 19:11 UTC, amoedoamorim commented
> @danielevalverde not sure if I am missing a detail, but I noticed there is a type of item that I can send to spam, but not restore on the item page:

I remember seeing code for displaying the restore button specifically for Parent or Main items only.
I think Child / Similar media would be sent to trash / restored via the main item.
That being a suggested similar item, I'm not sure how it should behave.

2023-09-19 20:03 UTC, brianfleming commented
> > @danielevalverde not sure if I am missing a detail, but I noticed there is a type of item that I can send to spam, but not restore on the item page:
> 
> I remember seeing code for displaying the restore button specifically for Parent or Main items only. I think Child / Similar media would be sent to trash / restored via the main item. That being a suggested similar item, I'm not sure how it should behave.

Interesting. I think the best thought then would be to try to confirm if this is still true. As a user, if I can send something to the trash/spam, I think I should be able to restore it the same way. So unless we discover a specific reason, I say we remove that restriction

2023-09-22 16:31 UTC, danielevalverde commented
@amoedoamorim and  @brianfleming , thanks for all the feedbacks :) 
Done: 
use ButtonMain instead of Button from MaterialUI :white_check_mark: 
remove unused query fields :white_check_mark: 
add onFailure handler :white_check_mark: 
remove the restriction to show "restore from Trash/ mask as Not Spam" when the item is a suggestion :white_check_mark: 

Please review it when you have some time. Thank you :pray:

2023-09-22 16:36 UTC, amoedoamorim commented on src/app/components/media/RestoreProjectMedia.js
> +        setFlashMessage('Failed to restore the item. Please try again later.', 'error');
Please review this: use the translatable message with the correct message type (I think 'error')

2023-09-22 16:36 UTC, brianfleming approved these changes
Thanks for the awesome changes @danielevalverde 
![spam](https://github.com/meedan/check-web/assets/418001/1d287be6-317d-4b61-86ae-12ecb50d2efb)

2023-09-22 16:37 UTC, amoedoamorim commented on src/app/components/media/RestoreProjectMedia.js
> +    <React.Fragment>
React.Fragment around a single component seems unnecessary

2023-09-22 16:40 UTC, amoedoamorim commented on src/app/components/media/RestoreProjectMedia.js
> +  team: graphql`
is this fragment used anywhere?

2023-09-22 16:43 UTC, amoedoamorim requested changes
Dani, I left a couple of notes, please review them! :pray:

2023-09-26 14:52 UTC, amoedoamorim approved these changes
:lgtm: :100:

2023-09-26 16:41 UTC, merged