Should be able to create claims without fact-checks.
meedan/check-web pull request #2086
Opened 2024-08-31 21:09 UTC by caiosba

## Description

- [ ] Pre-select default language in articles forms
- [ ] Fix "unknown language" bug
- [ ] These fields should not required anymore: fact-check title, fact-check summary and language
- [ ] If fact-check fields are not ready, the "Unpublished Report" button should be disabled and display a tooltip
- [ ] In the articles cards, display claim title if there is no fact-check

Reference: CV2-5134.

## Type of change

- [ ] Performance improvement and/or refactoring (non-breaking change that keeps existing functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Security mitigation or enhancement
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Automated test (add or update automated tests)

## How has this been tested?

Manually.

## Checklist

- [x] I have performed a self-review of my own code
- [x] I've made sure my branch is runnable and given good testing steps in the PR description
- [x] I considered secure coding practices when writing this code. Any security concerns are noted above.
- [ ] I have commented my code in hard-to-understand areas, if any
- [ ] I have made needed changes to the README
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] If I implemented any new components, they are self-contained, their `propTypes` are declared and they use React Hooks and, if data-fetching is required, they use Relay Modern with fragment containers
- [ ] If my components involve user interaction - specifically button, text fields, or other inputs - I have added a [BEM-like class name](https://meedan.atlassian.net/wiki/spaces/ENG/pages/1327628289/Naming+conventions+for+interactive+elements) to the element that is interacted with
- [ ] To the best of my knowledge, any new styles are applied according to the design system
- [ ] If I added a new external dependency, I included a rationale for doing so and an estimate of the change in bundle size (e.g., checked in https://bundlephobia.com/)
- [ ] If I touched a file that included an eslint-disable-file header, I updated the code such that the disabler can be removed

2024-09-01 15:30 UTC, brianfleming commented
Just one additional clarification about your steps in the PR @caiosba for the last item:
> In the articles cards, display claim title if there is no fact-check

You probably were already going to do this, but just to make sure:
Also show the claim "additional context" in the card description area if available.

So the logic is:
If there is a fact-check show the `title` and `summary`, if not, try to show the `claim title` and `additional context`

2024-09-01 15:31 UTC, caiosba commented
Yes that's clear, but thanks for putting it written here, @brianfleming !

2024-09-02 15:10 UTC, brianfleming reviewed
@caiosba just a quick 👻 check in on this and its looking good.
I think its probably local data, hopefully, but I am still seeing the unknown language in the dropdown. Again, not sure if this is something to be concerned about, since you cannot select it. Just looks confusing:

<img width="702" alt="Screenshot 2024-09-02 at 11 08 17 AM" src="https://github.com/user-attachments/assets/f85d2225-3b21-47e7-b94c-251890d58d50">

2024-09-02 15:39 UTC, brianfleming requested changes
I did find an issue @caiosba 
Take a look at the clip below. If I start to add a fact-check, then back out. I can still publish.
Its not in the clip, but if I remove the content from those fields, then still hit the create and publish button, the "old" content is actually saved and will be on the report page

https://github.com/user-attachments/assets/14525b9b-9d98-4653-9927-28eb45d9377b

2024-09-02 16:02 UTC, caiosba commented
Thanks @brianfleming :ghost: 
I'm going to work on this last bug you reported. For the "unknown language", maybe it's an existing fact-check you had that actually had the language saved as such?

2024-09-02 16:30 UTC, caiosba commented
> Code LGTM. Suggestion: introduce a helper function for the repeated testing of "value exists and is not a - placeholder, otherwise use that"

Done!

2024-09-02 16:37 UTC, caiosba commented
I fixed the "create & publish" bug, @brianfleming , please review :ghost:

2024-09-02 16:56 UTC, brianfleming approved these changes
Thanks @caiosba we can get this into QA and let Jessie try to find any issues now I think.

I am going to approve, so I don't hold you up, afterall i am a 👻 
but one thing to fix before merging, is that when you return the "combo" tooltip, there is a missing space in `reportFact-Check Title` because you are combining phrases I believe

<img width="327" alt="Screenshot 2024-09-02 at 12 52 35 PM" src="https://github.com/user-attachments/assets/7c3d10e5-d14c-48a4-8375-bbabd195aed2">

2024-09-02 17:30 UTC, caiosba commented
> Thanks @caiosba we can get this into QA and let Jessie try to find any issues now I think.
> 
> I am going to approve, so I don't hold you up, afterall i am a 👻 but one thing to fix before merging, is that when you return the "combo" tooltip, there is a missing space in `reportFact-Check Title` because you are combining phrases I believe
> 
> <img alt="Screenshot 2024-09-02 at 12 52 35 PM" width="327" src="https://private-user-images.githubusercontent.com/418001/363755374-7c3d10e5-d14c-48a4-8375-bbabd195aed2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUyOTY2NzQsIm5iZiI6MTcyNTI5NjM3NCwicGF0aCI6Ii80MTgwMDEvMzYzNzU1Mzc0LTdjM2QxMGU1LWQxNGMtNDhhNC04Mzc1LWJiYWJkMTk1YWVkMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwMlQxNjU5MzRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yMmJmNmVkNzMxYmZkY2RjY2NiOTFmNjFjYmZiNzgwMmVmNTgyNGZjYTYxODZjZDYzYjg4NTUyMTlkYjkyMzYxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.jQxQ5VYW_87N_n-UgIVT-AbV-EHNHbmd89igcQuPlOQ">

Ah, right! I just fixed it by making sure we only show one message in the tooltip each time.

2024-09-02 19:07 UTC, merged