Feature/cv2-4502 articles trash action
meedan/check-web pull request #2098
Opened 2024-09-11 07:23 UTC by sarahkeh

- [ ] Create button, add to edit slideout
- [ ] Attach confirm proceed dialog, add copy from Brian
- [ ] Get data for attached media items, if the article has them (new data piece? existing data?)
- [ ] Hook up Proceed to new trash API 
- [ ] After user confirms trash: 
   - [ ] Slideout is closed
   - [ ] List of articles is updated to no longer show article
   - [ ] Media items that were linked to the article no longer show article
   - [ ] Number of articles goes down
 - [ ] Unit test

## Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context.

References: TICKET-ID-1, TICKET-ID-2, …, TICKET-ID-N

## Type of change

- [ ] Performance improvement and/or refactoring (non-breaking change that keeps existing functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Security mitigation or enhancement
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Automated test (add or update automated tests)

## How has this been tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can verify the changes. Please describe whether or not you implemented automated tests.

## Things to pay attention to during code review

Please describe parts of the change that require extra attention during code review, for example:

- File FFFF, line LL: This refactoring does this and this. Is it consistent with how it’s implemented elsewhere?
- Etc.

## Checklist

- [ ] I have performed a self-review of my own code
- [ ] I've made sure my branch is runnable and given good testing steps in the PR description
- [ ] I considered secure coding practices when writing this code. Any security concerns are noted above.
- [ ] I have commented my code in hard-to-understand areas, if any
- [ ] I have made needed changes to the README
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] If I implemented any new components, they are self-contained, their `propTypes` are declared and they use React Hooks and, if data-fetching is required, they use Relay Modern with fragment containers
- [ ] If my components involve user interaction - specifically button, text fields, or other inputs - I have added a [BEM-like class name](https://meedan.atlassian.net/wiki/spaces/ENG/pages/1327628289/Naming+conventions+for+interactive+elements) to the element that is interacted with
- [ ] To the best of my knowledge, any new styles are applied according to the design system
- [ ] If I added a new external dependency, I included a rationale for doing so and an estimate of the change in bundle size (e.g., checked in https://bundlephobia.com/)
- [ ] If I touched a file that included an eslint-disable-file header, I updated the code such that the disabler can be removed

2024-09-19 15:05 UTC, brianfleming requested changes
Looking great @sarahkeh couple very nit picky things:

1. For the main text of the confirm dialogs I think you should add tagName="p" to the FormattedMessage component so the layout give a little space between the paragraph and the <Alert... component. See the screenshots below vs the similar delete list dialog:

<img width="611" alt="Screenshot 2024-09-19 at 10 52 33 AM" src="https://github.com/user-attachments/assets/9ea8b2c8-05cd-4902-9f07-10a305fb86d9">

## Versus
<img width="611" alt="Screenshot 2024-09-19 at 10 54 12 AM" src="https://github.com/user-attachments/assets/6bfda9d8-f761-45d1-a5a6-6e2fad23258c">


2. Seeing the dialogs in real life makes me think that ^^ main text is visually too long and should be separated out to make it more readable. Can you change it so it ends of being separate paragraphs? Same text really, but like this:

### Fact-Checks:

> Are you sure? If you send this article to the trash it will no longer be available to be associated with media responses.
>
> It can be removed from the Trash later, but it will be deleted permanently after 30 days.

### Explainers:

> Are you sure? If you send this article to the trash it will no longer be available to be associated with media responses.
> 
> If this article is currently associated with media, the link between the media and article will be removed.
> 
> It can be linked again if the article is removed from the Trash. After 30 days, this article will be permanently deleted.

2024-09-19 15:06 UTC, brianfleming commented on src/app/components/article/ArticleTrash.js
> +      <FormattedMessage
There are others, just wanted to point out one of them

2024-09-19 15:07 UTC, brianfleming commented
@sarahkeh one other thing i forgot to mention in my review and not sure if this is a local data thing or a bug, but take a look at this screenshot. Its me sending a fact-check to the trash, the message doesn't include the alert, but mentions that its associated with media, which it isn't. So I am just unsure of why I am see this dialog:

<img width="1093" alt="Screenshot 2024-09-19 at 11 06 25 AM" src="https://github.com/user-attachments/assets/5a3f705e-30af-4bf5-8e43-eeebcef8ffd5">

2024-09-20 17:12 UTC, sarahkeh commented
@brianfleming I think I got everything:

1. added p tags 
2. Broke up messages (this is probably better for translation, too, so repetitive sentences aren't translated more than once" 
3. fixed that Claim/fact-check without media issue

<img width="675" alt="Screenshot 2024-09-20 at 10 10 55 AM" src="https://github.com/user-attachments/assets/e767f26a-aab6-48f5-9749-8b96872742a3">
<img width="691" alt="Screenshot 2024-09-20 at 10 12 06 AM" src="https://github.com/user-attachments/assets/0aabfee1-4445-4d61-9a76-e57398c01d90">
<img width="732" alt="Screenshot 2024-09-20 at 10 11 53 AM" src="https://github.com/user-attachments/assets/351b65c4-de10-4226-ab63-90ea1abcc31b">

2024-09-20 17:19 UTC, brianfleming approved these changes
nice! thanks for the changes @sarahkeh approving, but since I only play a developer on TV, make sure one of the real ones takes a look!

![trash-panda](https://github.com/user-attachments/assets/967961d0-ab45-44b6-9fe8-74ce647e4114)

2024-09-20 17:25 UTC, brianfleming commented
Oh, one thing @sarahkeh 
since we don't have restore yet, or the list yet, maybe this and all those things should go into an epic branch instead of develop?
cc @caiosba @amoedoamorim

2024-09-20 17:27 UTC, caiosba commented
Good point, @brianfleming ! @sarahkeh please create an epic branch `epic/CV2-4441-articles-trash` and make it the base branch for this PR. We can merge the epic branch to `develop` once CV2-5069 and CV2-5319 are done.

2024-09-25 13:46 UTC, amoedoamorim approved these changes
:lgtm:

2024-09-25 14:36 UTC, merged