Epic/CV2-4111: Workspace analytics
meedan/check-web pull request #2107
Opened 2024-09-13 14:31 UTC by danielevalverde

## Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context.

References: TICKET-ID-1, TICKET-ID-2, …, TICKET-ID-N

## Type of change

- [ ] Performance improvement and/or refactoring (non-breaking change that keeps existing functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Security mitigation or enhancement
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Automated test (add or update automated tests)

## How has this been tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can verify the changes. Please describe whether or not you implemented automated tests.

## Things to pay attention to during code review

Please describe parts of the change that require extra attention during code review, for example:

- File FFFF, line LL: This refactoring does this and this. Is it consistent with how it’s implemented elsewhere?
- Etc.

## Checklist

- [ ] I have performed a self-review of my own code
- [ ] I've made sure my branch is runnable and given good testing steps in the PR description
- [ ] I considered secure coding practices when writing this code. Any security concerns are noted above.
- [ ] I have commented my code in hard-to-understand areas, if any
- [ ] I have made needed changes to the README
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] If I implemented any new components, they are self-contained, their `propTypes` are declared and they use React Hooks and, if data-fetching is required, they use Relay Modern with fragment containers
- [ ] If my components involve user interaction - specifically button, text fields, or other inputs - I have added a [BEM-like class name](https://meedan.atlassian.net/wiki/spaces/ENG/pages/1327628289/Naming+conventions+for+interactive+elements) to the element that is interacted with
- [ ] To the best of my knowledge, any new styles are applied according to the design system
- [ ] If I added a new external dependency, I included a rationale for doing so and an estimate of the change in bundle size (e.g., checked in https://bundlephobia.com/)
- [ ] If I touched a file that included an eslint-disable-file header, I updated the code such that the disabler can be removed

2024-10-29 22:45 UTC, brianfleming commented on src/app/components/dashboard/Dashboard.module.css
> +    .dashboard-two-column {
will start to review this @amoedoamorim just adding a quick comment that I think if you add `flex-wrap: wrap;` to this, then we will get some nice reponsiveness on the dashboard

2024-10-30 01:35 UTC, sarahkeh commented on src/app/components/dashboard/TimelineArticlesCreatedAndUpdated.js
> +  console.log('TimelineArticlesCreatedAndUpdated statistics:', statistics.number_of_articles_created_by_date); // eslint-disable-line no-console
Are these console statements still needed?

2024-10-30 01:55 UTC, sarahkeh commented on src/app/components/media/MediaTypeDisplayName.js
> +    description: 'Label to show that the type of media is was imported into the application',
small typo, 'is' should be removed

2024-10-30 13:46 UTC, brianfleming requested changes
@amoedoamorim et al. Couple Changes found while reviewing and one question:
- Can we update the page title for dashboard to match the other patterns? As you can see in this screenshot the page title still references the All page after I go to the dashboard
<img width="378" alt="Screenshot 2024-10-30 at 9 39 24 AM" src="https://github.com/user-attachments/assets/fd1e5a71-6d80-46d9-a1a5-a351e64eb24b">


- One situation that I missed during the review of the stacked bar is when one of the slices is 0 and it appears last. As you can see in the screenshot below, the visual looks a bit broken because the right side doesn't end up rounded. Really it should always have a rounded end since that the container, compare the two here, let me know if my poor explanation could be better
<img width="550" alt="Screenshot 2024-10-30 at 9 37 25 AM" src="https://github.com/user-attachments/assets/29ddd945-b222-41a0-bb1d-1eea9ac507df">

## Question
Not sure how much control we have over this via the viz package, but if you look at the screenshot below you can see that the timeline dates can get in weird spacing situations, anything we can do?
<img width="1289" alt="Screenshot 2024-10-30 at 9 38 00 AM" src="https://github.com/user-attachments/assets/e795a74f-dfe5-4bd9-b5e9-e03c2ba967da">

2024-10-30 13:57 UTC, brianfleming commented
Another small thing to address @amoedoamorim 
Article tags are "the same" as media tags, so this empty state can go to the tags settings just like media:

<img width="368" alt="Screenshot 2024-10-30 at 9 56 11 AM" src="https://github.com/user-attachments/assets/e35937ba-b6e5-4992-98bc-f9f72f9b3d02">

2024-10-30 17:16 UTC, caiosba commented
Tested locally and works well!

2024-10-30 17:24 UTC, sarahkeh approved these changes
I left a couple tiny comments, but looks good! The display components all follow the same pattern so it's easy to read.

2024-10-30 18:23 UTC, amoedoamorim commented
> Not sure how much control we have over this via the viz package, but if you look at the screenshot below you can see that the timeline dates can get in weird spacing situations, anything we can do?

@brianfleming yeah, that sucks. I found it seems to occur at random times but if you navigate away and back then the timeline looks evenly spaced with the same data. Since this looks like a weird occasional edge case, I'll save this for last as it will probably take more research, trial and error than the other fixes I need to get in.

2024-10-30 18:24 UTC, brianfleming commented
> > Not sure how much control we have over this via the viz package, but if you look at the screenshot below you can see that the timeline dates can get in weird spacing situations, anything we can do?
> 
> @brianfleming yeah, that sucks. I found it seems to occur at random times but if you navigate away and back then the timeline looks evenly spaced with the same data. Since this looks like a weird occasional edge case, I'll save this for last as it will probably take more research, trial and error than the other fixes I need to get in.

yeah thats what I figured @amoedoamorim 
agree, leave till the end and I don't think we consider it a release blocker either

2024-10-30 22:17 UTC, brianfleming approved these changes
great, thanks for those changes @amoedoamorim 
agreed, lets get this to QA and find out all the other things we need to do!

2024-10-30 22:19 UTC, merged