Refactoring/8675 remove page classes
meedan/check-web pull request #703
Opened 2020-09-11 20:53 UTC by danielevalverde

2020-09-11 21:00 UTC, caiosba requested changes
Looks great, thanks Dani! Can we just remove this last comment that references `Page`/?
```
$ grep -r Page test/spec/*
test/spec/app_spec.rb:    $caller_name = example.metadata[:description_args]  # for Page#go()
```

2020-09-11 21:00 UTC, caiosba commented
Looks great, thanks Dani! Can we just remove this last comment that references `Page`/?
```
$ grep -r Page test/spec/*
test/spec/app_spec.rb:    $caller_name = example.metadata[:description_args]  # for Page#go()
```

2020-09-11 21:46 UTC, danielevalverde commented
> Looks great, thanks Dani! Can we just remove this last comment that references `Page`/?
> 
> ```
> $ grep -r Page test/spec/*
> test/spec/app_spec.rb:    $caller_name = example.metadata[:description_args]  # for Page#go()
> ```



> Looks great, thanks Dani! Can we just remove this last comment that references `Page`/?
> 
> ```
> $ grep -r Page test/spec/*
> test/spec/app_spec.rb:    $caller_name = example.metadata[:description_args]  # for Page#go()
> ```

I deleted the comment :)

2020-09-12 22:01 UTC, caiosba approved these changes

2020-09-12 22:03 UTC, merged