Replace props.intl.formatMessage with <FormattedMessage />
meedan/check-web pull request #719
Opened 2020-10-04 19:31 UTC by gabrielrab

Hi!
I am sending my PR to resolve [Issue #20](https://github.com/meedan/check/issues/20)

2020-10-08 12:47 UTC, amoedoamorim requested changes
Thanks you @gabrielrab for your contribution! We appreciate it! In order for it to be accepted and merged please apply the requested changes.

2020-10-08 12:47 UTC, amoedoamorim commented on src/app/components/media/CreateRelatedMediaDialog.js
> +            <FormattedMessage {...globalStrings.cancel}/>
Please insert a space after the closing curly brace `} />`

2020-10-08 12:47 UTC, amoedoamorim commented on src/app/components/task/EditTaskDialog.js
> +            <FormattedMessage id='singleChoiceTask.addValue' defaultMessage='Add Option'/>
Please use double quotes for strings

2020-10-08 12:47 UTC, amoedoamorim commented on src/app/components/task/EditTaskDialog.js
> +            <FormattedMessage id='singleChoiceTask.addOther'  defaultMessage='Add "Other"'  />
Please use double quotes for `id` string. Fine to leave `defaultMessage` as is

2020-10-08 13:12 UTC, gabrielrab commented
@amoedoamorim 
I complete change requests

2020-10-08 14:18 UTC, amoedoamorim requested changes
Sorry, can you please also fix these? Have you tried building the app locally? Again, thanks for contributing!

2020-10-08 14:18 UTC, amoedoamorim commented on src/app/components/task/EditTaskDialog.js
> +            <FormattedMessage id="singleChoiceTask.addOther"  defaultMessage='Add "Other"'  />
239:63  error  Multiple spaces found before 'defaultMessage'  no-multi-spaces
239:93  error  Multiple spaces found before '/'               no-multi-spaces

2020-10-12 11:46 UTC, gabrielrab commented
@amoedoamorim 
I can run only check-web or i need run all check stack ?

2020-10-21 19:35 UTC, amoedoamorim commented
> I can run only check-web or i need run all check stack ?
Hi @gabrielrab , sorry for taking so long to reply. Are you still around? While you theoretically could do it, you'd need to manually install whatever dependencies are needed. The supported way to run Check is to build and run the whole stack.

2020-10-28 00:07 UTC, amoedoamorim requested changes
Hey @gabrielrab ! Thanks for contributing! We appreciate it! Please apply the requested changes so we can accept and merge your PR!

2020-10-28 20:29 UTC, amoedoamorim commented
Hello @gabrielrab , are you still around? Please let me know if you're still interested in fixing this!

2020-10-29 02:01 UTC, gabrielrab commented
@amoedoamorim yes, I'm here! I am also interested in solving this problem.

2020-10-29 13:31 UTC, amoedoamorim commented
> @amoedoamorim yes, I'm here! I am also interested in solving this problem.

That's nice! There are some simple changes requested, please fix them before someone else does!

2020-11-01 00:07 UTC, gabrielrab commented
@amoedoamorim before 45 minutes of the second half, I solved the problem. Sorry for the delay !

2020-11-02 22:58 UTC, merged