Substitute props.intl.formatMessage with <FormattedMessage />
meedan/check-web pull request #720
Opened 2020-10-05 07:54 UTC by michizhou

Replaced several instances of `props.intl.formatMessage` with `<FormattedMessage />` where a string is passed for the pages rendered by `UserInfoEdit.js` and `SlackConfig.js`
Helps to resolve meedan/check#20

2020-10-22 18:44 UTC, amoedoamorim requested changes
Hello @michizhou ! Thanks so much for your interest in contributing, we appreciate it! In order for us to be able to accept your PR please apply the requested changes! Have a great Hacktoberfest!

2020-10-22 18:44 UTC, amoedoamorim commented on src/app/components/source/UserInfoEdit.js
> +                  />
Here you should use `<FormattedMessage {...globalStrings.edit} />`

2020-10-22 18:44 UTC, amoedoamorim commented on src/app/components/source/UserInfoEdit.js
> +                    defaultMessage={messages.addLink.defaultMessage}
The desired usage is that the actual content of these keys is moved here, and `addLink` is to be removed from the `messages` object.

2020-10-22 18:44 UTC, amoedoamorim commented on src/app/components/source/UserInfoEdit.js
> +                  />
Here you should use `<FormattedMessage {...globalStrings.cancel} />`

2020-10-22 18:44 UTC, amoedoamorim commented on src/app/components/source/UserInfoEdit.js
> +                  />
Here you should use `<FormattedMessage {...globalStrings.save} />`

2020-10-22 18:44 UTC, amoedoamorim commented on src/app/components/team/SlackConfig.js
> +              defaultMessage={messages.title.defaultMessage}
The desired usage is that the actual content of these keys is moved here, and `title` is to be removed from the `messages` object.

2020-10-22 18:44 UTC, amoedoamorim commented on src/app/components/team/SlackConfig.js
> +              />
Here you should use `<FormattedMessage {...globalStrings.cancel} />`

2020-10-22 18:44 UTC, amoedoamorim commented on src/app/components/team/SlackConfig.js
> +              />
Here you should use `<FormattedMessage {...globalStrings.save} />`

2020-10-22 20:05 UTC, michizhou commented
@amoedoamorim I have made some of the requested changes, though it seems the SlackConfig.js file has been deleted and reorganized into an index.js file that handles some of the changes already (I already resolved the merge conflict). Please let me know if any additional changes or modifications need to be made. Thank you.

2020-10-22 20:20 UTC, amoedoamorim requested changes
Thanks @michizhou . There are still some minor details that need fixing, which are some left trailing spaces, and there's a major one: `FormattedMessage` is not defined. Please include it in the import statement in line 4.

2020-10-22 20:20 UTC, amoedoamorim commented on src/app/components/source/UserInfoEdit.js
> +                <FormattedMessage
Please remove trailing spaces

2020-10-22 20:20 UTC, amoedoamorim commented on src/app/components/source/UserInfoEdit.js
> +                  <FormattedMessage
Please remove trailing spaces

2020-10-22 20:27 UTC, michizhou commented
@amoedoamorim My apologies for not catching those minor errors in my prior commits. I have made the necessary changes in my latest commit above. If there is anything else that needs to be fixed, please let me know.

2020-10-27 23:11 UTC, amoedoamorim approved these changes
Thanks for contributing @michizhou ! We appreciate it! Your PR looks good and will be merged!

2020-10-27 23:13 UTC, merged

2020-11-10 18:08 UTC, danielafeitosa commented
Hi @michizhou!

For your contribution to CheckWeb during [Meedan Hacktoberfest 2020](https://meedan.com/hacktoberfest) you are eligible to earn a swag :tada: 
To receive it please fill in the form with your information: https://forms.gle/qKMRkWK7CEccCtGv5

Thank you!