Replace `props.intl.formatMessage` with `<FormattedMessage />`
meedan/check-web pull request #727
Opened 2020-10-09 11:44 UTC by tony-ho

Replace in-JSX occurrences of the `props.intl.formatMessage` expression with the `<FormattedMessage />` component.

The following conventions have been used for consistency with the existing code:
- Messages defined in `globalStrings` are passed using spread operator.
- Local messages props are passed inline to the `FormattedMessage` component and the key removed from the `messages` object.

The `TeamInviteMembers.newInvite` id has been updated to camel case `teamInviteMembers.newInvite` for consistency with the other message IDs in `TeamInviteMembers.js`.

Finally, the generated react-intl localizations have been updated.

Fixes meedan/check#20

2020-10-28 20:40 UTC, amoedoamorim requested changes
Hello @tony-ho ! Thank you so much for your contribution! We appreciate it! Sorry to take so long to review it! Please fix some minor details so we can accept and merge it! Also please review these files and remove `injectIntl` from the import statement where it's no longer needed.

2020-10-28 20:40 UTC, amoedoamorim commented on src/app/components/team/TeamInviteMembers.js
> +          <DialogTitle><FormattedMessage id="teamInviteMembers.newInvite" defaultMessage="Invite members" /></DialogTitle>
Please keep same `id`: `TeamInviteMembers.newInvite`

2020-10-28 20:40 UTC, amoedoamorim commented on src/app/components/user/AttributionDialog.js
> +import { FormattedMessage, injectIntl } from 'react-intl';
Please remove `injectIntl` from the import and the respective usage

2020-10-28 20:40 UTC, amoedoamorim commented on src/app/components/user/UserEmail.js
> +              <FormattedMessage id="uuserEmail.skip" defaultMessage="Skip" />
Please keep same `id`: `userEmail.skip`

2020-10-29 10:21 UTC, tony-ho commented
@amoedoamorim Thanks for the review. The requested changes have been resolved and `injectIntl` has been removed where no longer used.

2020-10-29 15:24 UTC, merged

2020-11-10 18:09 UTC, danielafeitosa commented
Hi @tony-ho !

For your contribution to CheckWeb during [Meedan Hacktoberfest 2020](https://meedan.com/hacktoberfest) you are eligible to earn a swag :tada: 
To receive it please fill in the form with your information: https://forms.gle/qKMRkWK7CEccCtGv5

Thank you!