Removed inline styling
meedan/check-web pull request #744
Opened 2020-10-23 08:06 UTC by K-Kumar-01

Changed the styling by material ui box component
Some changes made using styled components

Some functionalities like `cursor:pointer` and `backgroundImage` are not available as JSX attributes . So had to use styled component there.
Rest all has been done using material ui box

2020-10-27 23:21 UTC, amoedoamorim commented on src/app/components/task/DatetimeRespondTask.js
> +                    defaultMessage="Pick a date"
Please do not alter copy!

2020-10-27 23:22 UTC, amoedoamorim commented on src/app/components/task/DatetimeRespondTask.js
> +                      <EventIcon />
Please do not alter icon!

2020-10-27 23:22 UTC, amoedoamorim commented on src/app/components/task/DatetimeRespondTask.js
> +                margin="normal"
Please do not alter input format!

2020-10-27 23:48 UTC, amoedoamorim requested changes
Hello @K-Kumar-01 ! It's good to see you around here again! Thanks for this new PR, it looks much better than the first one. I'm sorry I failed to explicit that we DO use double quotes for element attributes, so in places like `<Box clone justifyContent='flex-start' alignItems='center'>` these should actually be double quotes! Please update your PR with the changes requested so I we can accept it!

2020-10-27 23:48 UTC, amoedoamorim commented on src/app/components/user/AttributionDialog.js
> +          <Box my={units(2)}>
Please make it `my={2}` instead of `my={units(2)}`

2020-10-27 23:48 UTC, amoedoamorim commented on src/app/components/task/Task.js
> +              <Box component='span' lineHeight='24px' px={units(1)}>
Please remove the `units()` call around `1`. Make it `px={1}` instead.

2020-10-27 23:48 UTC, amoedoamorim commented on src/app/components/task/EditTaskDialog.js
> +      <Box mt={units(2)}>
Please make it `mt={2}`. In general, remove all `units()` calls when using `Box`.

2020-10-27 23:48 UTC, amoedoamorim commented on src/app/components/task/EditTaskDialog.js
> +              <Box clone p={`${units(0.5)} ${units(1)}`} width={"75%"}>
Please remove `units` call

2020-10-27 23:48 UTC, amoedoamorim commented on src/app/components/task/EditTaskDialog.js
> +        <Box mt={units(2)} >
Please remove units call. Make it `mt={2}` instead.

2020-10-27 23:48 UTC, amoedoamorim commented on src/app/components/task/GeolocationRespondTask.js
> +        <Box color={black54} fontFamily={fontStackSans} fontWeight={400} fontSize={units(1.5)} lineHeight={units(2.5)}>
Please revert. This is better handled with the material-ui `Typography` component.

2020-10-27 23:48 UTC, amoedoamorim commented on src/app/components/task/GeolocationTaskResponse.js
> +import { units, black05, black38, FlexRow, black54 } from '../../styles/js/shared';
What is `black54` being imported for?

2020-10-27 23:48 UTC, amoedoamorim commented on src/app/components/task/Task.js
> +              <Box component='span' lineHeight='24px' px={units(1)}>
Please remove `units()` call. I think you got the idea already!

2020-10-28 06:40 UTC, K-Kumar-01 commented
@amoedoamorim 
I have made the requested changes in the new PR. 
Tell me if there is any further change needed.

2020-10-29 14:53 UTC, amoedoamorim requested changes
Hello @K-Kumar-01 ! Thanks for your changes. We're almost there. There are still some changes needed to comply with coding guidelines. I'm pasting the eslint output to make it easier to detect what needs to change. Please fix those so we can accept and merge it! Thanks a lot!

2020-10-29 14:53 UTC, amoedoamorim commented on src/app/components/task/GeolocationRespondTask.js
> +          <Box height={'400px'}>
`height="400px"`

`375:23  error  Curly braces are unnecessary here  react/jsx-curly-brace-presence`

2020-10-29 14:53 UTC, amoedoamorim commented on src/app/components/task/GeolocationRespondTask.js
>          <div>
Please remove this `div` as the newly added `Box` should take its place.

2020-10-29 14:53 UTC, amoedoamorim commented on src/app/components/task/EditTaskDialog.js
> +        <Box mt={2} >
`mt={1}`

2020-10-29 14:53 UTC, amoedoamorim commented on src/app/components/task/DatetimeRespondTask.js
> +              <Box clone justifyContent='flex-start' alignItems='center'>
`214:41  error  Unexpected usage of singlequote                  jsx-quotes`
`214:65  error  Unexpected usage of singlequote                  jsx-quotes`

2020-10-29 14:53 UTC, amoedoamorim commented on src/app/components/task/DatetimeRespondTask.js
> +                        taskTimezones && taskTimezones.length ? taskTimezones : Object.values(timezones)
`246:1   error  Line 246 exceeds the maximum line length of 100  max-len`

2020-10-29 14:53 UTC, amoedoamorim commented on src/app/components/task/DatetimeRespondTask.js
> +          </FlexRow>
`271:21  error  Trailing spaces not allowed                      no-trailing-spaces`

2020-10-29 14:53 UTC, amoedoamorim commented on src/app/components/task/EditTaskDialog.js
> +              <Box clone py={0.5} px={1} width={"75%"}>
`width="75%"`
`218:48  error  Curly braces are unnecessary here  react/jsx-curly-brace-presence`

2020-10-29 14:53 UTC, amoedoamorim commented on src/app/components/task/GeolocationTaskResponse.js
> +          <Box component="span"
`67:16  error  Property should be placed on a new line  react/jsx-first-prop-new-line`

2020-10-29 14:53 UTC, amoedoamorim commented on src/app/components/task/SingleChoiceTask.js
> +            <Box display="flex" justifyContent="flex-start" alignItems="center"
Please break props into lines.

`168:18  error  Property should be placed on a new line             react/jsx-first-prop-new-line`
`168:33  error  Prop `justifyContent` must be placed on a new line  react/jsx-max-props-per-line`

2020-10-29 14:53 UTC, amoedoamorim commented on src/app/components/task/Task.js
> +    }
401:6   error  Trailing spaces not allowed  no-trailing-spaces

2020-10-29 14:53 UTC, amoedoamorim commented on src/app/components/task/Task.js
> +                <Box
441:21  error  Trailing spaces not allowed  no-trailing-spaces

2020-10-29 14:53 UTC, amoedoamorim commented on src/app/components/task/Task.js
> +          <Box
462:15  error  Trailing spaces not allowed  no-trailing-spaces

2020-10-29 14:53 UTC, amoedoamorim commented on src/app/components/task/Task.js
> +            className="task__resolver"
463:39  error  Trailing spaces not allowed  no-trailing-spaces

2020-10-29 14:53 UTC, amoedoamorim commented on src/app/components/task/Task.js
> +      <Box
512:11  error  Trailing spaces not allowed  no-trailing-spaces

2020-10-29 14:53 UTC, amoedoamorim commented on src/app/components/task/Task.js
> +        </Box>
698:15  error  Trailing spaces not allowed  no-trailing-spaces

2020-10-29 14:53 UTC, amoedoamorim commented on src/app/components/team/TeamBots.js
> +
203:1  error  Trailing spaces not allowed  no-trailing-spaces

2020-10-29 14:53 UTC, amoedoamorim commented on src/app/components/team/TeamInfoEdit.js
> +`;
Please revert. Using `styled-components` is not in the scope of this ticket.

2020-10-29 14:53 UTC, amoedoamorim commented on src/app/components/team/TeamInfoEdit.js
> +              imageUrl={avatarPreview || team.avatar}
Please revert. Using `styled-components` is not in the scope of this ticket.

2020-10-29 14:53 UTC, amoedoamorim commented on src/app/components/team/TeamInviteMembers.js
> +                </Row>
305:23  error  Trailing spaces not allowed  no-trailing-spaces

2020-10-29 14:53 UTC, amoedoamorim commented on src/app/components/team/TeamMembersComponent.js
> +              </Card>
90:22  error  Trailing spaces not allowed  no-trailing-spaces

2020-10-29 14:59 UTC, K-Kumar-01 commented
@amoedoamorim 
I will fix these changes ASAP

2020-10-29 15:56 UTC, amoedoamorim requested changes
Great, thanks! There are still some trailing spaces. Looks like you created those when fixing the other issues.

2020-10-29 15:56 UTC, amoedoamorim commented on src/app/components/task/GeolocationTaskResponse.js
> +          <Box
`57:15  error  Trailing spaces not allowed  no-trailing-spaces`

2020-10-29 15:56 UTC, amoedoamorim commented on src/app/components/task/SingleChoiceTask.js
> +              justifyContent="flex-start"
168:17  error  Trailing spaces not allowed  no-trailing-spaces
169:29  error  Trailing spaces not allowed  no-trailing-spaces
170:42  error  Trailing spaces not allowed  no-trailing-spaces

2020-10-30 12:37 UTC, amoedoamorim commented
Please update your branch with latest `develop` and watch out for conflicts: `src/app/components/user/AttributionDialog.js`

2020-10-30 14:35 UTC, K-Kumar-01 commented
@amoedoamorim 
I have updated my `develop` branch with the latest code from original. Let me if there are any changes required.

2020-10-30 19:58 UTC, amoedoamorim requested changes
Thanks @K-Kumar-01 ! There are still some trailing spaces left! Please fix those and we should be in a good position to merge! Thank you so much for your effort in contributing! We appreciate it!

2020-10-30 19:58 UTC, amoedoamorim commented on src/app/components/task/GeolocationTaskResponse.js
> +          <Box
^ This is still unfixed

2020-10-30 19:58 UTC, amoedoamorim commented on src/app/components/task/SingleChoiceTask.js
> +              justifyContent="flex-start"
^ These are still unfixed

2020-10-31 04:55 UTC, K-Kumar-01 commented
@amoedoamorim I have removed the trailing spaces which were left
Let me if there is any change required.

2020-11-02 21:59 UTC, amoedoamorim requested changes
Hey @K-Kumar-01 , thanks again! I notices a couple details left that are blocking the build. Please fix those so we can move on! Thank you!

2020-11-02 21:59 UTC, amoedoamorim commented on src/app/components/search/SearchResultsTable/FillRemainingHeight.js
> +import Box from '@material-ui/core/Box'
3:40  error  Missing semicolon  semi

2020-11-02 21:59 UTC, amoedoamorim commented on src/app/components/task/Task.js
> +              <Box
418:19  error  Trailing spaces not allowed  no-trailing-spaces

2020-11-03 05:55 UTC, K-Kumar-01 commented
@amoedoamorim Made the requested changes that were causing build error

2020-11-08 14:45 UTC, amoedoamorim commented
Thanks @K-Kumar-01 and congrat's on your approved PR! That looks amazing now, I'll go ahead and merge it! Thank you so much for the effort you put in your contribution! We appreciate it!

2020-11-08 14:45 UTC, merged