Replace inline stylings with Material-UI Box attributes
meedan/check-web pull request #748
Opened 2020-10-27 20:05 UTC by amaaniqbal

This PR replaces inline stylings present in `tag/` and `team/` directories inside `check-web/src/app/components/` with the corresponding Material-UI `Box` component attributes.

Fixes [#18](https://github.com/meedan/check/issues/18)

2020-10-27 23:20 UTC, amoedoamorim requested changes
Thanks @amaaniqbal for your contribution! We appreciate it! Please notice that it won't work if you don't import material-ui `Box` on those files! Please fix as needed so we are able to accept it! Thanks again for contributing!

2020-10-28 15:06 UTC, amaaniqbal commented
Oops, missed it! Fixing it right away...

2020-10-29 14:13 UTC, amoedoamorim requested changes
Hello @amaaniqbal ! Thank you so much for your interest in contributing! Please notice that some coding standards need to be met and we require a few changes to accept this PR. I kindly ask you to review your PR and apply these changes. Mainly the string props should be enclosed in double quotes, and unused imports should be removed.

2020-10-29 14:13 UTC, amoedoamorim commented on src/app/components/team/TeamBots.js
> +          <Box pb={5} display='flex' alignItems='center' justifyContent='center'>
Please use double quotes for string props/attributes.

`192:31  error  Unexpected usage of singlequote  jsx-quotes`

2020-10-29 14:13 UTC, amoedoamorim commented on src/app/components/team/TeamReport.js
> +          <Box mt={2} display='flex' alignItems='end' justifyContent='end'>
Please use double quotes for string props/attributes.

`89:31  error  Unexpected usage of singlequote    jsx-quotes`

2020-10-29 14:13 UTC, amoedoamorim commented on src/app/components/team/TeamTags.js
> -          padding: units(2),
Please remove units from import statement.

`27:10  error  'units' is defined but never used  no-unused-vars`

2020-10-29 14:13 UTC, amoedoamorim commented on src/app/components/team/TeamTags.js
> +                  <Box pb={5} display='flex' alignItems='center'>
Please use single quotes for string props/attributes.

`489:39  error  Unexpected usage of singlequote    jsx-quotes`

2020-10-29 14:13 UTC, amoedoamorim commented on src/app/components/team/TeamReport.js
> -          <p style={{ marginTop: units(2), textAlign: 'end' }}>
Please remove units from import statement.

12:25 error 'units' is defined but never used no-unused-vars

2020-10-29 18:21 UTC, amaaniqbal commented
@amoedoamorim I did the suggested changes. Please have a look!

2020-10-30 20:08 UTC, amoedoamorim commented
Thanks @amaaniqbal for your contribution! We appreciate it! There are a couple of conflicts in your PR in relation to current `develop` branch. Would you solve these so we can move forward with merging your code, please?

2020-10-31 04:12 UTC, amaaniqbal commented
Fixed the conflicts @amoedoamorim!

2020-11-03 13:14 UTC, amaaniqbal commented
@amoedoamorim any more changes required?

2020-11-09 13:21 UTC, amoedoamorim commented
Hello @amaaniqbal ! Thanks for your contribution! We appreciate it! Your PR looks good in general, but there are some conflicts resulting from merges of PRs from others. Please solve those so we can go ahead and merge yours!

2020-11-19 16:27 UTC, amaaniqbal commented
Fixed the merge conflicts again @amoedoamorim!

2020-12-04 14:03 UTC, alexmeedan commented
Hello @amaaniqbal, I was away for the past weeks and was unable to merge your PR. Would you please fix this conflict so I can merge your PR? Thank you!

2020-12-04 14:42 UTC, amaaniqbal commented
Hello @alexmeedan, this PR was up since Hacketoberfest and since then I am just resolving merge conflicts. I resolved them once again, but please review this before merging any other PRs this time if possible. Also, please consider this as a part of Hacktoberfest.

PS: `src/app/components/team/TeamProjects.js` was deleted by someone which resulted in merge conflicts, so I added it back. Let me know if it should be deleted, and I will remove the same.

2020-12-04 14:53 UTC, alexmeedan commented
Yes, I'll merge as soon as it's fixed! I couldn't do it before because your previous commit was sent in while I was away. It will still count for Hacktoberfest and eligible for Meedan swag. I apologize for the inconvenience. The file `TeamProjects.js` is not in use anymore and should be deleted.

2020-12-04 15:08 UTC, amaaniqbal commented
Thanks a lot for the positive response @alexmeedan! I removed the unused file `TeamProjects.js`. You can review the PR now.

2020-12-07 13:20 UTC, amoedoamorim commented
Hello @amaaniqbal . I did some fixing, merging and cleaning up myself and merged your contribution on another branch. Thanks again for participating in Hacktoberfest with Meedan! We appreciate your contribution!

2020-12-07 13:20 UTC, closed without merging

2020-12-07 16:57 UTC, amaaniqbal commented
Thanks a lot for merging my changes @amoedoamorim! I can see them in the PR over [here](https://github.com/meedan/check-web/pull/768). May I know what made my previous commits fail Travis build and your commit passed? 
PS: I am just curious to know this.