Test/161 unit tests team list components
meedan/check-web pull request #788
Opened 2021-01-19 21:33 UTC by danielevalverde

2021-01-19 22:06 UTC, caiosba commented on src/app/components/team/TeamLists/TeamListsColumn.test.js
> +  it('should render collum', () => {
Typo on `collum`

2021-01-19 22:06 UTC, caiosba commented on src/app/components/team/TeamLists/TeamListsColumn.test.js
> +      title="Colum title"
Typo on `Colum`

2021-01-19 22:09 UTC, caiosba commented on src/app/components/team/TeamLists/TeamListsColumn.test.js
> +});
Would be great to test this condition: https://github.com/meedan/check-web/blob/develop/src/app/components/team/TeamLists/TeamListsColumn.js#L56-L59

This means:

- In the test above, make sure that the "placeholder" doesn't appear
- Add another test where `columns` is empty and make sure that the placeholder appears

2021-01-19 22:12 UTC, caiosba commented on src/app/components/team/TeamLists/TeamListsItem.test.js
> +    expect(wrapper.html()).toMatch('Hide');
I would add this here too: `expect(wrapper.html()).not.toMatch('Show');`

2021-01-19 22:12 UTC, caiosba commented on src/app/components/team/TeamLists/TeamListsItem.test.js
> +    expect(wrapper.html()).toMatch('Show');
I would add this here too: `expect(wrapper.html()).not.toMatch('Hide');`

2021-01-19 22:13 UTC, caiosba commented on src/app/components/team/TeamLists/TeamListsItem.test.js
> +});
Other cases that would be good to test:

1) Arrows are displayed only if both `onMoveUp` and `onMoveDown` are provided (https://github.com/meedan/check-web/blob/develop/src/app/components/team/TeamLists/TeamListsItem.js#L68)

2) Metadata label is displayed for metadata columns (https://github.com/meedan/check-web/blob/develop/src/app/components/team/TeamLists/TeamListsItem.js#L90)

2021-01-19 22:14 UTC, caiosba requested changes
Please take a look at my inline comments - overall, great work!

2021-01-21 20:55 UTC, amoedoamorim approved these changes

2021-01-22 14:02 UTC, merged