Feature/check 209 sources metadata
meedan/check-web pull request #795
Opened 2021-01-25 11:56 UTC by melsawy

2021-01-26 23:53 UTC, amoedoamorim requested changes
I'm not sure if the annotated_type and parent_type mean the same thing. I see we have both in the code but I would favor a single usage, unless they mean different things. While we don't clarify this, I think the `annotated={source}` change is an important one.

2021-01-27 04:53 UTC, melsawy commented on src/app/components/task/Task.js
> +    const task = { ...teamTask };
Yes I got this error `Cannot add property cannotAct, object is not extensible` when working direct to `this.props.task`

2021-01-27 04:55 UTC, melsawy commented on src/app/components/team/CreateTeamTask.js
> +      associated_type: this.props.associatedType,
It was `annotated_type` but Caio suggest `associated_type` in ticket description and I agreed about this name as we used `annotated_type` & `annotated_id` when refer to object but here we just need to know the `associated_type` either `ProjectMedia` or `Source`

2021-01-27 05:04 UTC, melsawy commented on src/app/components/annotations/Annotation.js
> +        parent_type: parentType,
for this one I suggest to keep `parent_type` to be consist which commit other mutations like comment, flags, etc

2021-01-27 05:07 UTC, melsawy commented on src/app/components/task/Task.js
> +        parent_type: parentType,
I suggest to keep `parent_type` same other annotations mutation and file a ticket for refactor this field in all related mutations 
what do you think?

2021-01-27 09:17 UTC, melsawy commented on src/app/components/source/SourceInfo.js
> +      <Tasks tasks={sourceMetadata} media={source} fieldset="metadata" noscroll />
for sure but it required to change in multiple files and extra testing for summit different type of annotations currently I am running in stable version and I'd like to merge to `develop` ASAP so I suggest to file a ticket with this refactor and work on it after merging stable version what do you think @amoedoamorim ?

2021-01-27 14:24 UTC, amoedoamorim commented on src/app/components/task/Task.js
> +    const task = { ...teamTask };
Alright. I see, thanks Sawy, that makes sense. We should not mutate Relay data directly. Let's leave it as is for now and perhaps we can come up with a better pattern, maybe passing cannotAct as a separate prop on it's own.

2021-01-27 15:02 UTC, merged